IWYU: missing include for std::atomic in FixedQueue.h
Fix build error using libstdc++ due to missing include for usage of
std::atomic in FixedQueue.h:
    ../../third_party/angle/src/common/FixedQueue.h:61:10: error: ‘atomic’ in namespace ‘std’ does not name a template type
       61 |     std::atomic<size_type> mSize;
          |          ^~~~~~

Bug: chromium:957519
Change-Id: I099a4a8c463149d74cf82ec6eda5e4a872d6e812
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/4352888
Reviewed-by: Shahbaz Youssefi <syoussefi@chromium.org>
Commit-Queue: Shahbaz Youssefi <syoussefi@chromium.org>