Android: improve error message due to missing trace libs
I think this only happens when angle_restricted_traces wasn't set in gn
args, resulting in traces outside of the apk.

Previously we'd get a confusing error about missing gen/tracegz...
files, now we get this:

    I15:55:48.527742Z Syncing harry_potter_hogwarts_mystery trace (1/1)
    Error: missing library: libangle_restricted_traces_harry_potter_hogwarts_mystery.so
    Is angle_restricted_traces set in gn args?

Also removed swallowing errors in _PushLibToAppDir, crashing seems
better than running with out of date files.

Bug: b/294861737
Change-Id: I5696f35a910f6db2310d90e112a83881af3a8f50
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/4781569
Commit-Queue: Roman Lavrov <romanl@google.com>
Reviewed-by: Cody Northrop <cnorthrop@google.com>